# # arithmetic function

In [3]:
import numpy as np

In [15]:
v1 = np.array([1,2,3,4,5,7,3,1,5,8,9])
print("minimum: ", np.min(v1))
print("maximum: ", np.max(v1))
print("minimum: ", np.min(v1), np.argmin(v1))
print("maximum: ", np.max(v1), np.argmax(v1))
print("sqar root: ", np.sqrt(v1))

minimum:  1
maximum:  9
minimum:  1 0
maximum:  9 10
sqar root:  [1.         1.41421356 1.73205081 2.         2.23606798 2.64575131
 1.73205081 1.         2.23606798 2.82842712 3.        ]


In [13]:
v2 = np.array([[2,1,3],[9,5,6]])
print(np.min(v2, axis=0))

[2 1 3]


In [19]:
v2 = np.array([2,1,3])
print(np.sin(v2))
print(np.cos(v2))
print(np.cumsum(v2))

[0.90929743 0.84147098 0.14112001]
[-0.41614684  0.54030231 -0.9899925 ]
[2 3 6]
