# arithmetic operation

In [3]:
import numpy as np

In [11]:
var = np.array([1,2,3,4,5])

varadd = var+3
varsub = var-3
varmul = var*3
varmol = var % 3
vardiv = var/3
print(varadd)
print(varsub)
print(varmul)
print(varmol)
print(vardiv)

[4 5 6 7 8]
[-2 -1  0  1  2]
[ 3  6  9 12 15]
[1 2 0 1 2]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [22]:
var= np.array([1,2,3,4,5])
varadd = np.reciprocal(var)
print(varadd)

[1 0 0 0 0]


In [9]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])

varadd = var1 + var2
print(varadd)

[ 2  4  6  8 10]


In [15]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])

varadd = np.add(var1, var2)
print(varadd)

[ 2  4  6  8 10]


In [17]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])

varadd = np.add(var1, 5)
print(varadd)

[ 6  7  8  9 10]


# 2d array

In [20]:
var3 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
var4 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
print(var3)
print(var4)
varadd = var3 + var4
print(varadd)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
