# data type

In [3]:
import numpy as np

In [7]:
var = np.array([1,2,3,4,11,12,13,14,15])
print("data type : ", var.dtype)

data type :  int32


In [9]:
var = np.array([1.1,1.2,1.3])
print("data type : ", var.dtype)

data type :  float64


In [11]:
var = np.array(["a","d","t"])
print("data type : ", var.dtype)

data type :  <U1


In [13]:
var = np.array([1,2,3,"a","d","t",4,11,12,13,14,15])
print("data type : ", var.dtype)

data type :  <U11


In [23]:
x = np.array([1,2,3,4], dtype = np.int8)
y = np.array([1,2,3,4])
print("data type : ", x.dtype, y.dtype)
print (x)

data type :  int8 int32
[1 2 3 4]


In [25]:
x = np.array([1,2,3,4], dtype = "f")
y = np.array([1,2,3,4])
print("data type : ", x.dtype, y.dtype)
print (x)

data type :  float32 int32
[1. 2. 3. 4.]


In [29]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)

new1 = np.int_(new)
# y2 = np.array([1,2,3,4])
print("data type : ", x2.dtype)
print("data type : ", new.dtype)
print("data type : ", new1.dtype)
print(x2)
print(new)
print(new1)

data type :  int32
data type :  float32
data type :  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [33]:
x3 = np.array([1,2,3,4])
new2 = x3.astype(float)

print(x3)
print(new2)

[1 2 3 4]
[1. 2. 3. 4.]
