In [2]:
import numpy as np

In [8]:
#zeros
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [10]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
#ones
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [16]:
#empty

ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [20]:
#range
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [22]:
#diagonal
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [32]:
#linesapce
ar_lin = np.linspace(1,10,num=5)
ar_lin1 = np.linspace(0,20,num=5)
print(ar_lin)
print(ar_lin1)

[ 1.    3.25  5.5   7.75 10.  ]
[ 0.  5. 10. 15. 20.]
