## array

In [12]:
import numpy as np

In [23]:
x = [1,2,3,4]

y= np.array([1,2,3,4,5])

print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [18]:
l = []

for i in range(1,5):
    int_1 = input("enter : ")
    l.append(int_1)

print(np.array(l))

enter :  12
enter :  15
enter :  18
enter :  17


['12' '15' '18' '17']


In [20]:
l = []

for i in range(1,5):
    int_1 = int(input("enter : "))
    l.append(int_1)

print(np.array(l))

enter :  12
enter :  13
enter :  14
enter :  15


[12 13 14 15]


types of array
1. 1-D: [1,2,3]
2. 2-D:[[1,2,3]]
3. 3-D:[[[1,2,3]]]
4. HIGHER DIMENSIONAL ARRAY: 

print(y.ndim) # check dimension kon sa hai


In [30]:
ar2 = np.array([[1,2,3],[4,5,6]])
print(ar2)
print(ar2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [32]:
ar2 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(ar2)
print(ar2.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [40]:
arn = np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
