In [2]:
import numpy as np

In [6]:
#rand()
var = np.random.rand(5)

print(var)

[0.95003275 0.2967071  0.84412223 0.91481843 0.8390808 ]


In [12]:
var1 = np.random.rand(2,5)
print(var1)

[[0.96966996 0.53294759 0.87191549 0.89693982 0.02059774]
 [0.68232453 0.16017799 0.50875213 0.82300444 0.01552715]]


In [16]:
#randn()
var2 = np.random.randn(5)
print(var2)

[-1.11044422 -0.38033686 -0.01300471  2.8898043  -0.15960858]


In [18]:
#ranf()
var3 = np.random.ranf(5)
print(var3)

[0.8616551  0.10987288 0.97712431 0.09218687 0.41242238]


In [20]:
#randit()
#var4 = np.random.randint(min,max,total_values)
var4 = np.random.randint(5,20,5)
print(var4)

[16 18  7 12 18]
