# shape and resize

In [3]:
import numpy as np

In [5]:
var = np.array([[1,2],[1,2]])
print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [7]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var1.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [13]:
var1 = np.array([1,2,3,4], ndmin=4)

print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


# reshape

In [18]:
v = np.array([1,2,3,4,5,6,7,7,8,9])
x = v.reshape(5,2)
print(v.ndim)
print(x)

[[1 2]
 [3 4]
 [5 6]
 [7 7]
 [8 9]]
